// Smallest check that the native boundary holds end to end: a real
// gb::GameBoy built from a ROM, one frame run, pixels back out.
//
// Runs under Electron (via ELECTRON_RUN_AS_NODE, set by `npm test`) rather
// than plain node, because the addon is compiled against Electron's ABI --
// a second node-ABI build just for tests would be a second build to keep
// working. core/gb's own unit tests cover the emulation itself.
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

// Both consoles run at 59.7275Hz, so one emulated frame is worth this many
// audio frames at 48kHz. What's asserted is the rate, not the content: the
// synthetic ROMs here make no sound, and silence is still samples.
const AUDIO_FRAMES_PER_FRAME = 48000 / 59.7275;

function assertAudioRate(core, label) {
  // Drain whatever earlier frames left queued, or it counts toward the
  // window being measured.
  while (core.readAudio(2048).length > 0) {
    // keep draining
  }

  let frames = 0;
  for (let i = 0; i < 20; i++) {
    core.runFrame();
    frames += core.readAudio(2048).length / 2;
  }
  const expected = AUDIO_FRAMES_PER_FRAME * 20;
  assert.ok(
    Math.abs(frames - expected) < expected * 0.05,
    `${label}: got ${frames} audio frames over 20 emulated frames, expected about ${Math.round(expected)}`,
  );
}

// Snapshot, run on, restore, and check the picture is the one from before.
// A state that saves but doesn't restore looks fine until someone relies on
// it, so the check is the round trip, not that the call returned bytes.
function assertStateRoundTrip(core, label) {
  const state = core.saveState();
  assert.ok(state.length > 0, `${label}: empty savestate`);

  const before = Buffer.from(core.frame());
  for (let i = 0; i < 10; i++) core.runFrame();
  assert.strictEqual(core.loadState(state), true, `${label}: loadState refused its own state`);
  assert.ok(Buffer.from(core.frame()).equals(before), `${label}: frame differs after restoring`);
}

const gb = require('../build/Release/gb_addon.node');
const gba = require('../build/Release/gba_addon.node');
const ds = require('../build/Release/ds_addon.node');

// Generated by core/gb/tools/gen_test_rom and checked into the shared repo
// as base64. It draws vertical black/white stripes across the whole screen,
// so a correctly rendered frame has to contain both ends of the palette.
const source = fs.readFileSync(
  path.join(__dirname, '..', 'vendor', 'multiemu', 'app', 'src', 'testRom.ts'),
  'utf8',
);
const rom = Buffer.from(source.match(/'([A-Za-z0-9+/=]{100,})'/)[1], 'base64');

const gameBoy = new gb.GameBoy(new Uint8Array(rom));
gameBoy.runFrame();

const frame = gameBoy.frame();
assert.strictEqual(frame.length, gameBoy.width * gameBoy.height * 4);

const shades = new Set();
for (let i = 0; i < frame.length; i += 4) {
  shades.add(frame[i]);
  assert.strictEqual(frame[i + 3], 0xff, `pixel ${i / 4} is not opaque`);
}
assert.ok(
  shades.has(0x00) && shades.has(0xff),
  `expected black and white stripes, got shades ${[...shades]}`,
);

// The palette maps shade -> RGBA, so grey is grey: R, G and B must match.
assert.strictEqual(frame[0], frame[1]);
assert.strictEqual(frame[1], frame[2]);

assert.strictEqual(gameBoy.audioSampleRate, 48000);
assertAudioRate(gameBoy, 'Game Boy');

// The stripes ROM above never touches the sound registers, so it proves the
// rate but not that anything can actually be heard. This one is fourteen
// hand-assembled SM83 instructions that switch the APU on and hold a note
// on square channel 1.
//
// Execution starts at 0x0100, which is where the cartridge header begins, so
// the entry point is the usual jump over it and the code lives at 0x0150.
const toneRom = Buffer.alloc(0x8000);
Buffer.from([0xc3, 0x50, 0x01]).copy(toneRom, 0x100); // jp $0150
Buffer.from([
  0x3e, 0x80, 0xe0, 0x26, // ld a,$80 / ldh [$26],a -- NR52: power on
  0x3e, 0x77, 0xe0, 0x24, // ld a,$77 / ldh [$24],a -- NR50: full volume
  0x3e, 0xff, 0xe0, 0x25, // ld a,$FF / ldh [$25],a -- NR51: both sides
  0x3e, 0x80, 0xe0, 0x11, // ld a,$80 / ldh [$11],a -- NR11: 50% duty
  0x3e, 0xf0, 0xe0, 0x12, // ld a,$F0 / ldh [$12],a -- NR12: volume 15
  0x3e, 0x00, 0xe0, 0x13, // ld a,$00 / ldh [$13],a -- NR13: frequency low
  0x3e, 0x87, 0xe0, 0x14, // ld a,$87 / ldh [$14],a -- NR14: trigger
  0x18, 0xfe,             // jr -2 -- hold the note
]).copy(toneRom, 0x150);
// 0x00 at 0x147 is "ROM ONLY", which is what gb::loadCartridge checks.

const singing = new gb.GameBoy(new Uint8Array(toneRom));
for (let i = 0; i < 10; i++) singing.runFrame();

const tone = singing.readAudio(4096);
let tonePeak = 0;
for (const sample of tone) tonePeak = Math.max(tonePeak, Math.abs(sample));
assert.ok(tonePeak > 0, 'the tone ROM produced silence');

assert.throws(() => new gb.GameBoy(new Uint8Array(16)), /invalid ROM header/);

// --- Game Boy link cable ---------------------------------------------------
//
// One byte across the cable, each way. The master sends 0x11 on its own
// clock, the slave waits on it with 0x22, and each writes whatever it
// received into BGP, the background palette. The screen is all colour 0,
// whose shade is BGP's low two bits -- so the picture itself says what came
// across: 0x22 gives shade 2 on the master, 0x11 shade 1 on the slave. A
// master with no cable reads 0xFF instead (shade 3, black), and that is the
// control: the colours below only happen if the bytes really swapped.
function linkTestRom(send, control) {
  const romBytes = Buffer.alloc(0x8000);
  Buffer.from([0xc3, 0x50, 0x01]).copy(romBytes, 0x100); // jp $0150
  Buffer.from([
    0x3e, send, 0xe0, 0x01, //    ld a,send / ldh [$01],a    -- SB
    0x3e, control, 0xe0, 0x02, // ld a,ctl / ldh [$02],a     -- SC: start
    0xf0, 0x02,             // wait: ldh a,[$02]
    0xcb, 0x7f,             //    bit 7,a                    -- still busy?
    0x20, 0xfa,             //    jr nz,wait
    0xf0, 0x01,             //    ldh a,[$01]                -- what came in
    0xe0, 0x47,             //    ldh [$47],a                -- BGP
    0x18, 0xfe,             //    jr -2
  ]).copy(romBytes, 0x150);
  return new Uint8Array(romBytes);
}
const masterRom = linkTestRom(0x11, 0x81); // drives the clock
const slaveRom = linkTestRom(0x22, 0x80);  // waits on the other's

const cabled = new gb.GbLink(masterRom, slaveRom);
assert.strictEqual(cabled.width, 160);
assert.strictEqual(cabled.height, 288, 'two screens');
for (let i = 0; i < 5; i++) cabled.runFrame();
const cabledFrame = cabled.frame();
const slaveScreen = 160 * 144 * 4;
assert.strictEqual(cabledFrame.length, 160 * 288 * 4);
assert.strictEqual(cabledFrame[0], 0x55, 'the master did not receive 0x22');
assert.strictEqual(cabledFrame[slaveScreen], 0xaa, 'the slave did not receive 0x11');
assert.strictEqual(cabled.hasBattery(0), false);
cabled.setPlayer(1);
cabled.setButton(4, true);
assert.ok(cabled.readAudio(4096) instanceof Int16Array);
cabled.close();

const uncabled = new gb.GameBoy(masterRom);
for (let i = 0; i < 5; i++) uncabled.runFrame();
assert.strictEqual(uncabled.frame()[0], 0x00, 'with no cable the master should read 0xFF');

assert.throws(() => new gb.GbLink(masterRom, new Uint8Array(16)), /Jugador 2/);

// --- GBA -------------------------------------------------------------
//
// Hand-assembled rather than loaded from a real ROM: mGBA only needs two
// magic bytes to accept a file as GBA, so a synthetic one keeps this test
// free of anything copyrighted while still running real ARM code through
// the core.
const gbaRom = Buffer.alloc(1024);
gbaRom.writeUInt32LE(0xea00002e, 0x00); // b 0xC0 -- byte 3 is the 0xEA mGBA checks for
gbaRom[0xb2] = 0x96;                    // the second magic byte

// Switches on video mode 3 (a plain 16-bit bitmap) and puts one red pixel
// at the top left. Red specifically: it lands in a different byte from
// blue, so a wrong channel order shows up here instead of in someone's
// screenshot. (The Android port hit exactly that with melonDS's compositor
// swizzle -- see docs/desktop-port-handoff.md section 2.)
[
  0xe3a00404, // mov  r0, #0x04000000   (I/O base)
  0xe3a01b01, // mov  r1, #0x400        (BG2 enable)
  0xe3811003, // orr  r1, r1, #3        (+ video mode 3)
  0xe5801000, // str  r1, [r0]          (DISPCNT)
  0xe3a00406, // mov  r0, #0x06000000   (VRAM)
  0xe3a0101f, // mov  r1, #0x1F         (BGR555 red)
  0xe1c010b0, // strh r1, [r0]
  0xeafffffe, // b .
].forEach((word, i) => gbaRom.writeUInt32LE(word, 0xc0 + i * 4));

const advance = new gba.Gba(new Uint8Array(gbaRom));
assert.strictEqual(advance.width, 240);
assert.strictEqual(advance.height, 160);

// The first frame is still the pre-boot forced blank; the write lands after.
for (let i = 0; i < 3; i++) advance.runFrame();

const gbaFrame = advance.frame();
assert.strictEqual(gbaFrame.length, advance.width * advance.height * 4);
assert.deepStrictEqual([...gbaFrame.slice(0, 4)], [0xff, 0x00, 0x00, 0xff], 'top-left pixel should be red');
assert.deepStrictEqual([...gbaFrame.slice(4, 8)], [0x00, 0x00, 0x00, 0xff], 'its neighbour should be black');

assert.throws(() => new gba.Gba(new Uint8Array(1024)), /not a GBA ROM/);

// Audio comes out at the console's frame rate times the output rate. Getting
// this wrong is silent in the literal sense -- mGBA's own default is 96000Hz,
// and a mismatch here plays everything at the wrong speed rather than failing.
assert.strictEqual(advance.audioSampleRate, 48000);
assertAudioRate(advance, 'GBA');
assertStateRoundTrip(advance, 'GBA');

// close() has to hand the save file back to the OS there and then, not
// whenever the garbage collector gets round to the wrapper. Bringing a save
// down from the cloud replaces that file while the app is running, and on
// Windows an open handle makes the write fail outright -- which is exactly
// how this was found. Deleting it is the cheapest way to ask the OS whether
// the handle is really gone.
const closingSave = path.join(os.tmpdir(), 'multiemu-smoke-close.sav');
fs.writeFileSync(closingSave, Buffer.alloc(65536));
const closing = new gba.Gba(new Uint8Array(gbaRom), closingSave);
closing.runFrame();
closing.close();
fs.unlinkSync(closingSave); // EPERM/EBUSY here means the core never let go

// --- GBA link cable ---------------------------------------------------
//
// A real transfer over the cable, in the serial port's multiplayer mode --
// the one Pokemon's Cable Club uses. Both consoles run this ROM: each sends
// 0xBEEF, the parent starts a transfer and waits for it to finish, and each
// paints its first pixel green only once SIOMULTI1 (the child's word, as
// seen by everyone after a transfer) reads 0xBEEF. Unlinked, that register
// never holds it, so green on both screens means data genuinely crossed
// between the cores.
//
// The wait matters. An earlier version restarted a transfer the moment the
// last one ended and read SIOMULTI1 in that same instant, while it was
// already being reset for the next one -- and failed, though the cable was
// working. Real games wait for the busy bit too.
//
// So is the five-second pause before the first transfer. The link only
// attaches after a 240-frame warm-up, the parent a moment before the
// child, and a transfer started inside that window can leave the parent
// waiting for good -- 1 run in 3 did, before this. No real game asks for
// the link that early (Pokemon's Cable Club is minutes away), so the ROM
// behaves like one instead of like a stress test.
//
// Real time rather than stepped frames: the cores run on their own threads,
// and the link only attaches after a 240-frame warm-up (see gba_link.cpp).
const linkRom = Buffer.from(gbaRom);
[
  0xe3a00404, // 0C0      mov   r0, #0x04000000
  0xe3a01b01, // 0C4      mov   r1, #0x400
  0xe3811003, // 0C8      orr   r1, r1, #3
  0xe5801000, // 0CC      str   r1, [r0]            DISPCNT: mode 3, BG2
  0xe3a06406, // 0D0      mov   r6, #0x06000000     VRAM
  0xe3a0101f, // 0D4      mov   r1, #0x1F
  0xe1c610b0, // 0D8      strh  r1, [r6]            red: not linked yet
  0xe2800c01, // 0DC      add   r0, r0, #0x100      r0 = 0x04000100
  0xe3a01000, // 0E0      mov   r1, #0
  0xe1c013b4, // 0E4      strh  r1, [r0, #0x34]     RCNT = 0: serial modes
  0xe3a01a02, // 0E8      mov   r1, #0x2000
  0xe3811003, // 0EC      orr   r1, r1, #3
  0xe1c012b8, // 0F0      strh  r1, [r0, #0x28]     SIOCNT: multiplayer, 115200
  0xe3a04cbe, // 0F4      mov   r4, #0xBE00
  0xe38440ef, // 0F8      orr   r4, r4, #0xEF
  0xe1c042ba, // 0FC      strh  r4, [r0, #0x2A]     SIOMLT_SEND = 0xBEEF
  0xe3a05ff8, // 100      mov   r5, #0x3E0          green
  0xe3a07f4b, // 104      mov   r7, #300            frames to wait
  0xe1508fba, // 108 vbl: ldrh  r8, [r0, #-0xFA]    VCOUNT
  0xe35800a0, // 10C      cmp   r8, #160
  0x1afffffc, // 110      bne   vbl                 until vblank starts
  0xe1508fba, // 114 out: ldrh  r8, [r0, #-0xFA]
  0xe35800a0, // 118      cmp   r8, #160
  0x0afffffc, // 11C      beq   out                 and ends
  0xe2577001, // 120      subs  r7, r7, #1
  0x1afffff7, // 124      bne   vbl
  0xe1d022b8, // 128 loop: ldrh r2, [r0, #0x28]     SIOCNT
  0xe3120004, // 12C      tst   r2, #4              child?
  0x1a000004, // 130      bne   check               only the parent starts
  0xe3822080, // 134      orr   r2, r2, #0x80
  0xe1c022b8, // 138      strh  r2, [r0, #0x28]     start a transfer
  0xe1d022b8, // 13C wait: ldrh r2, [r0, #0x28]
  0xe3120080, // 140      tst   r2, #0x80           still busy?
  0x1afffffc, // 144      bne   wait
  0xe1d032b2, // 148 check: ldrh r3, [r0, #0x22]    SIOMULTI1
  0xe1530004, // 14C      cmp   r3, r4
  0x1afffff4, // 150      bne   loop
  0xe1c650b0, // 154      strh  r5, [r6]            green: linked
  0xeafffffe, // 158      b     .
].forEach((word, i) => linkRom.writeUInt32LE(word, 0xc0 + i * 4));

function sleep(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}
const GREEN = [0x00, 0xff, 0x00, 0xff];
const linkSaves = [0, 1].map((player) => path.join(os.tmpdir(), `multiemu-smoke-link-${player}.sav`));
for (const save of linkSaves) fs.writeFileSync(save, Buffer.alloc(65536));
const link = new gba.GbaLink(new Uint8Array(linkRom), linkSaves[0], new Uint8Array(linkRom), linkSaves[1]);
assert.strictEqual(link.width, 240);
assert.strictEqual(link.height, 320);
const secondScreen = 240 * 160 * 4;
let linkFrame;
for (let waited = 0; waited < 15000; waited += 250) {
  sleep(250);
  linkFrame = link.frame();
  if (GREEN.every((byte, i) => linkFrame[i] === byte && linkFrame[secondScreen + i] === byte)) break;
}
assert.strictEqual(linkFrame.length, 240 * 320 * 4);
assert.deepStrictEqual([...linkFrame.slice(0, 4)], GREEN, 'player 1 never received the other console');
assert.deepStrictEqual(
  [...linkFrame.slice(secondScreen, secondScreen + 4)], GREEN, 'player 2 never received the other console');
link.setPlayer(1);
link.setButton(0, true);
link.setPlayer(0);
link.setPaused(true);
sleep(50);
link.close(); // hangs here if the pause gate is not opened on close
for (const save of linkSaves) fs.unlinkSync(save); // and both saves were let go
assert.throws(
  () => new gba.GbaLink(new Uint8Array(gbaRom), linkSaves[0], new Uint8Array(1024), linkSaves[1]),
  /jugador 2/);

// --- DS ----------------------------------------------------------------
//
// melonDS validates a cart far more loosely than mGBA does -- an empty file
// is accepted and boots to a blank screen -- so there is no magic-bytes
// trick to build a meaningful synthetic ROM around, the way the GBA case
// does above. What this covers is the boundary either side of the core:
// construction, the stacked two-screen geometry, and the frame conversion
// producing a full opaque buffer without crashing. Actual picture fidelity
// on the DS is verified by hand against a commercial ROM.
const localDir = path.join(os.tmpdir(), 'multiemu-smoke');
fs.mkdirSync(localDir, { recursive: true });
ds.setLocalDir(localDir);

assert.throws(() => new ds.Ds(path.join(localDir, 'does-not-exist.nds')), /could not read/);

const blankRom = path.join(localDir, 'blank.nds');
fs.writeFileSync(blankRom, Buffer.alloc(4096));

const nintendoDs = new ds.Ds(blankRom);
assert.strictEqual(nintendoDs.width, 256);
assert.strictEqual(nintendoDs.height, 384, 'both screens, stacked');

for (let i = 0; i < 30; i++) nintendoDs.runFrame();

const dsFrame = nintendoDs.frame();
assert.strictEqual(dsFrame.length, nintendoDs.width * nintendoDs.height * 4);
for (let i = 3; i < dsFrame.length; i += 4) {
  assert.strictEqual(dsFrame[i], 0xff, `DS pixel ${(i - 3) / 4} is not opaque`);
}

assert.strictEqual(nintendoDs.audioSampleRate, 48000);
assertAudioRate(nintendoDs, 'DS');
assertStateRoundTrip(nintendoDs, 'DS');

// --- DS local wireless ---------------------------------------------------
//
// Structure only: a real wireless session needs a commercial game and is
// checked by hand. What this pins is everything around it -- both consoles
// running on their own threads (the active one's audio fills up, which it
// only does while its thread is emulating), all four screens in one frame,
// touch reaching either console, and closing while paused returning rather
// than hanging on a thread held at the pause gate.
const dsLinkSaves = [0, 1].map((player) => path.join(localDir, `link-${player}.sav`));
const dsLink = new ds.DsLink(blankRom, dsLinkSaves[0], blankRom, dsLinkSaves[1]);
assert.strictEqual(dsLink.width, 256);
assert.strictEqual(dsLink.height, 768, 'two consoles, two screens each');
sleep(500);
const dsLinkFrame = dsLink.frame();
assert.strictEqual(dsLinkFrame.length, 256 * 768 * 4);
for (let i = 3; i < dsLinkFrame.length; i += 4) {
  assert.strictEqual(dsLinkFrame[i], 0xff, `DS link pixel ${(i - 3) / 4} is not opaque`);
}
assert.ok(dsLink.readAudio(4000).length > 0, 'player 1 is not running');
dsLink.setPlayer(1);
sleep(200);
assert.ok(dsLink.readAudio(4000).length > 0, 'player 2 is not running');
dsLink.touch(10, 10, 1);
dsLink.setButton(0, true);
dsLink.releaseTouch();
dsLink.setPaused(true);
sleep(100);
dsLink.close(); // hangs here if the pause gate is not opened on close
assert.throws(
  () => new ds.DsLink(blankRom, dsLinkSaves[0], path.join(localDir, 'missing.nds'), dsLinkSaves[1]),
  /Jugador 2/);

// --- Release platform detection ----------------------------------------
//
// The update notice hangs on this, and the consequence of getting it wrong
// is offering an Android APK as an update to the desktop app. Both the
// field and the fallbacks are pinned: the field arrived late once already,
// and the fallbacks are what carried the check through that window.
const shared = require('../build/shared.js');

// The field the backend now serves takes priority, including when it
// disagrees with what the filename suggests.
assert.strictEqual(shared.isWindowsRelease({ platform: 'WINDOWS' }), true);
assert.strictEqual(shared.isWindowsRelease({ platform: 'ANDROID' }), false);
assert.strictEqual(
  shared.isWindowsRelease({ platform: 'ANDROID', apkUrl: 'x?filename%3D%22a.exe%22' }),
  false,
);

const androidRelease = {
  versionCode: 10,
  minAndroidSdk: 24,
  apkUrl: 'https://example/x?response-content-disposition=attachment%3B%20filename%3D%22multiemu-1.8.apk%22&x-id=GetObject',
};
const windowsRelease = {
  versionCode: 11,
  minAndroidSdk: null,
  apkUrl: 'https://example/x?response-content-disposition=attachment%3B%20filename%3D%22multiemu-1.0.exe%22&x-id=GetObject',
};

assert.strictEqual(shared.isWindowsRelease(androidRelease), false);
assert.strictEqual(shared.isWindowsRelease(windowsRelease), true);

// No filename to read: fall back to minAndroidSdk, and treat anything that
// looks like neither as not ours.
assert.strictEqual(shared.isWindowsRelease({ apkUrl: null, minAndroidSdk: 24 }), false);
assert.strictEqual(shared.isWindowsRelease({ apkUrl: null, minAndroidSdk: null }), true);

// --- Cloud save identity -----------------------------------------------
//
// This one is a contract with the Android app, not a local choice: the two
// only ever see each other's saves if the key matches exactly. It was wrong
// in all three ways at once once already -- no system prefix, zero-padded
// hex, and the battery save uploaded to a save-state slot.
assert.strictEqual(
  shared.cloudGameKey('gba', new Uint8Array(Buffer.from('multiemu'))),
  'gba:1bf63dba',
);
assert.strictEqual(
  shared.cloudGameKey('nds', new Uint8Array(Buffer.from('multiemu'))),
  'nds:1bf63dba',
);

// A CRC32 whose top nibble is zero must stay seven characters. Padding it
// to eight is what Android would never produce.
assert.strictEqual(
  shared.cloudGameKey('gb', new Uint8Array(Buffer.from('multiemu-0'))),
  'gb:1686969',
);

// --- Encoding ----------------------------------------------------------
//
// Every string the user sees is Spanish, and an editor or a script writing
// a file as cp1252 instead of UTF-8 turns one accent into a replacement
// character in the UI while everything still builds and runs. Cheap to
// check, and it already caught four files.
for (const file of [
  'src/hub.js',
  'src/save3ds.js',
  'scripts/publish.js',
  'src/main.js',
  'src/preload.js',
  'src/renderer/hub.js',
  'src/renderer/renderer.js',
  'src/renderer/audio.js',
  'src/renderer/index.html',
  'README.md',
]) {
  const bytes = fs.readFileSync(path.join(__dirname, '..', file));
  assert.ok(
    Buffer.compare(Buffer.from(bytes.toString('utf8'), 'utf8'), bytes) === 0,
    `${file} is not valid UTF-8`,
  );
}

// The 3DS cloud save: pure JS, so it lives in its own file and runs here too.
require('./save3ds.test.js');
// The publish script against a fake GitHub and Hub.
require('./publish.test.js');

console.log('smoke: ok');
