// Smallest check that the native boundary holds end to end: a real
// gb::GameBoy built from a ROM, one frame run, pixels back out.
//
// Runs under Electron (via ELECTRON_RUN_AS_NODE, set by `npm test`) rather
// than plain node, because the addon is compiled against Electron's ABI --
// a second node-ABI build just for tests would be a second build to keep
// working. core/gb's own unit tests cover the emulation itself.
const assert = require('assert');
const fs = require('fs');
const path = require('path');

const addon = require('../build/Release/gb_addon.node');

// Generated by core/gb/tools/gen_test_rom and checked into the shared repo
// as base64. It draws vertical black/white stripes across the whole screen,
// so a correctly rendered frame has to contain both ends of the palette.
const source = fs.readFileSync(
  path.join(__dirname, '..', 'vendor', 'multiemu', 'app', 'src', 'testRom.ts'),
  'utf8',
);
const rom = Buffer.from(source.match(/'([A-Za-z0-9+/=]{100,})'/)[1], 'base64');

const gameBoy = new addon.GameBoy(new Uint8Array(rom));
gameBoy.runFrame();

const frame = gameBoy.frame();
assert.strictEqual(frame.length, addon.SCREEN_WIDTH * addon.SCREEN_HEIGHT * 4);

const shades = new Set();
for (let i = 0; i < frame.length; i += 4) {
  shades.add(frame[i]);
  assert.strictEqual(frame[i + 3], 0xff, `pixel ${i / 4} is not opaque`);
}
assert.ok(
  shades.has(0x00) && shades.has(0xff),
  `expected black and white stripes, got shades ${[...shades]}`,
);

// The palette maps shade -> RGBA, so grey is grey: R, G and B must match.
assert.strictEqual(frame[0], frame[1]);
assert.strictEqual(frame[1], frame[2]);

assert.throws(() => new addon.GameBoy(new Uint8Array(16)), /invalid ROM header/);

console.log('smoke: ok');
