// Smallest check that the native boundary holds end to end: a real
// gb::GameBoy built from a ROM, one frame run, pixels back out.
//
// Runs under Electron (via ELECTRON_RUN_AS_NODE, set by `npm test`) rather
// than plain node, because the addon is compiled against Electron's ABI --
// a second node-ABI build just for tests would be a second build to keep
// working. core/gb's own unit tests cover the emulation itself.
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

// Both consoles run at 59.7275Hz, so one emulated frame is worth this many
// audio frames at 48kHz. What's asserted is the rate, not the content: the
// synthetic ROMs here make no sound, and silence is still samples.
const AUDIO_FRAMES_PER_FRAME = 48000 / 59.7275;

function assertAudioRate(core, label) {
  // Drain whatever earlier frames left queued, or it counts toward the
  // window being measured.
  while (core.readAudio(2048).length > 0) {
    // keep draining
  }

  let frames = 0;
  for (let i = 0; i < 20; i++) {
    core.runFrame();
    frames += core.readAudio(2048).length / 2;
  }
  const expected = AUDIO_FRAMES_PER_FRAME * 20;
  assert.ok(
    Math.abs(frames - expected) < expected * 0.05,
    `${label}: got ${frames} audio frames over 20 emulated frames, expected about ${Math.round(expected)}`,
  );
}

// Snapshot, run on, restore, and check the picture is the one from before.
// A state that saves but doesn't restore looks fine until someone relies on
// it, so the check is the round trip, not that the call returned bytes.
function assertStateRoundTrip(core, label) {
  const state = core.saveState();
  assert.ok(state.length > 0, `${label}: empty savestate`);

  const before = Buffer.from(core.frame());
  for (let i = 0; i < 10; i++) core.runFrame();
  assert.strictEqual(core.loadState(state), true, `${label}: loadState refused its own state`);
  assert.ok(Buffer.from(core.frame()).equals(before), `${label}: frame differs after restoring`);
}

const gb = require('../build/Release/gb_addon.node');
const gba = require('../build/Release/gba_addon.node');
const ds = require('../build/Release/ds_addon.node');

// Generated by core/gb/tools/gen_test_rom and checked into the shared repo
// as base64. It draws vertical black/white stripes across the whole screen,
// so a correctly rendered frame has to contain both ends of the palette.
const source = fs.readFileSync(
  path.join(__dirname, '..', 'vendor', 'multiemu', 'app', 'src', 'testRom.ts'),
  'utf8',
);
const rom = Buffer.from(source.match(/'([A-Za-z0-9+/=]{100,})'/)[1], 'base64');

const gameBoy = new gb.GameBoy(new Uint8Array(rom));
gameBoy.runFrame();

const frame = gameBoy.frame();
assert.strictEqual(frame.length, gameBoy.width * gameBoy.height * 4);

const shades = new Set();
for (let i = 0; i < frame.length; i += 4) {
  shades.add(frame[i]);
  assert.strictEqual(frame[i + 3], 0xff, `pixel ${i / 4} is not opaque`);
}
assert.ok(
  shades.has(0x00) && shades.has(0xff),
  `expected black and white stripes, got shades ${[...shades]}`,
);

// The palette maps shade -> RGBA, so grey is grey: R, G and B must match.
assert.strictEqual(frame[0], frame[1]);
assert.strictEqual(frame[1], frame[2]);

assert.strictEqual(gameBoy.audioSampleRate, 48000);
assertAudioRate(gameBoy, 'Game Boy');

// The stripes ROM above never touches the sound registers, so it proves the
// rate but not that anything can actually be heard. This one is fourteen
// hand-assembled SM83 instructions that switch the APU on and hold a note
// on square channel 1.
//
// Execution starts at 0x0100, which is where the cartridge header begins, so
// the entry point is the usual jump over it and the code lives at 0x0150.
const toneRom = Buffer.alloc(0x8000);
Buffer.from([0xc3, 0x50, 0x01]).copy(toneRom, 0x100); // jp $0150
Buffer.from([
  0x3e, 0x80, 0xe0, 0x26, // ld a,$80 / ldh [$26],a -- NR52: power on
  0x3e, 0x77, 0xe0, 0x24, // ld a,$77 / ldh [$24],a -- NR50: full volume
  0x3e, 0xff, 0xe0, 0x25, // ld a,$FF / ldh [$25],a -- NR51: both sides
  0x3e, 0x80, 0xe0, 0x11, // ld a,$80 / ldh [$11],a -- NR11: 50% duty
  0x3e, 0xf0, 0xe0, 0x12, // ld a,$F0 / ldh [$12],a -- NR12: volume 15
  0x3e, 0x00, 0xe0, 0x13, // ld a,$00 / ldh [$13],a -- NR13: frequency low
  0x3e, 0x87, 0xe0, 0x14, // ld a,$87 / ldh [$14],a -- NR14: trigger
  0x18, 0xfe,             // jr -2 -- hold the note
]).copy(toneRom, 0x150);
// 0x00 at 0x147 is "ROM ONLY", which is what gb::loadCartridge checks.

const singing = new gb.GameBoy(new Uint8Array(toneRom));
for (let i = 0; i < 10; i++) singing.runFrame();

const tone = singing.readAudio(4096);
let tonePeak = 0;
for (const sample of tone) tonePeak = Math.max(tonePeak, Math.abs(sample));
assert.ok(tonePeak > 0, 'the tone ROM produced silence');

assert.throws(() => new gb.GameBoy(new Uint8Array(16)), /invalid ROM header/);

// --- GBA -------------------------------------------------------------
//
// Hand-assembled rather than loaded from a real ROM: mGBA only needs two
// magic bytes to accept a file as GBA, so a synthetic one keeps this test
// free of anything copyrighted while still running real ARM code through
// the core.
const gbaRom = Buffer.alloc(1024);
gbaRom.writeUInt32LE(0xea00002e, 0x00); // b 0xC0 -- byte 3 is the 0xEA mGBA checks for
gbaRom[0xb2] = 0x96;                    // the second magic byte

// Switches on video mode 3 (a plain 16-bit bitmap) and puts one red pixel
// at the top left. Red specifically: it lands in a different byte from
// blue, so a wrong channel order shows up here instead of in someone's
// screenshot. (The Android port hit exactly that with melonDS's compositor
// swizzle -- see docs/desktop-port-handoff.md section 2.)
[
  0xe3a00404, // mov  r0, #0x04000000   (I/O base)
  0xe3a01b01, // mov  r1, #0x400        (BG2 enable)
  0xe3811003, // orr  r1, r1, #3        (+ video mode 3)
  0xe5801000, // str  r1, [r0]          (DISPCNT)
  0xe3a00406, // mov  r0, #0x06000000   (VRAM)
  0xe3a0101f, // mov  r1, #0x1F         (BGR555 red)
  0xe1c010b0, // strh r1, [r0]
  0xeafffffe, // b .
].forEach((word, i) => gbaRom.writeUInt32LE(word, 0xc0 + i * 4));

const advance = new gba.Gba(new Uint8Array(gbaRom));
assert.strictEqual(advance.width, 240);
assert.strictEqual(advance.height, 160);

// The first frame is still the pre-boot forced blank; the write lands after.
for (let i = 0; i < 3; i++) advance.runFrame();

const gbaFrame = advance.frame();
assert.strictEqual(gbaFrame.length, advance.width * advance.height * 4);
assert.deepStrictEqual([...gbaFrame.slice(0, 4)], [0xff, 0x00, 0x00, 0xff], 'top-left pixel should be red');
assert.deepStrictEqual([...gbaFrame.slice(4, 8)], [0x00, 0x00, 0x00, 0xff], 'its neighbour should be black');

assert.throws(() => new gba.Gba(new Uint8Array(1024)), /not a GBA ROM/);

// Audio comes out at the console's frame rate times the output rate. Getting
// this wrong is silent in the literal sense -- mGBA's own default is 96000Hz,
// and a mismatch here plays everything at the wrong speed rather than failing.
assert.strictEqual(advance.audioSampleRate, 48000);
assertAudioRate(advance, 'GBA');
assertStateRoundTrip(advance, 'GBA');

// --- DS ----------------------------------------------------------------
//
// melonDS validates a cart far more loosely than mGBA does -- an empty file
// is accepted and boots to a blank screen -- so there is no magic-bytes
// trick to build a meaningful synthetic ROM around, the way the GBA case
// does above. What this covers is the boundary either side of the core:
// construction, the stacked two-screen geometry, and the frame conversion
// producing a full opaque buffer without crashing. Actual picture fidelity
// on the DS is verified by hand against a commercial ROM.
const localDir = path.join(os.tmpdir(), 'multiemu-smoke');
fs.mkdirSync(localDir, { recursive: true });
ds.setLocalDir(localDir);

assert.throws(() => new ds.Ds(path.join(localDir, 'does-not-exist.nds')), /could not read/);

const blankRom = path.join(localDir, 'blank.nds');
fs.writeFileSync(blankRom, Buffer.alloc(4096));

const nintendoDs = new ds.Ds(blankRom);
assert.strictEqual(nintendoDs.width, 256);
assert.strictEqual(nintendoDs.height, 384, 'both screens, stacked');

for (let i = 0; i < 30; i++) nintendoDs.runFrame();

const dsFrame = nintendoDs.frame();
assert.strictEqual(dsFrame.length, nintendoDs.width * nintendoDs.height * 4);
for (let i = 3; i < dsFrame.length; i += 4) {
  assert.strictEqual(dsFrame[i], 0xff, `DS pixel ${(i - 3) / 4} is not opaque`);
}

assert.strictEqual(nintendoDs.audioSampleRate, 48000);
assertAudioRate(nintendoDs, 'DS');
assertStateRoundTrip(nintendoDs, 'DS');

// --- Release platform detection ----------------------------------------
//
// The update notice hangs on this, and the consequence of getting it wrong
// is offering an Android APK as an update to the desktop app. Both the
// field and the fallbacks are pinned: the field arrived late once already,
// and the fallbacks are what carried the check through that window.
const shared = require('../build/shared.js');

// The field the backend now serves takes priority, including when it
// disagrees with what the filename suggests.
assert.strictEqual(shared.isWindowsRelease({ platform: 'WINDOWS' }), true);
assert.strictEqual(shared.isWindowsRelease({ platform: 'ANDROID' }), false);
assert.strictEqual(
  shared.isWindowsRelease({ platform: 'ANDROID', apkUrl: 'x?filename%3D%22a.exe%22' }),
  false,
);

const androidRelease = {
  versionCode: 10,
  minAndroidSdk: 24,
  apkUrl: 'https://example/x?response-content-disposition=attachment%3B%20filename%3D%22multiemu-1.8.apk%22&x-id=GetObject',
};
const windowsRelease = {
  versionCode: 11,
  minAndroidSdk: null,
  apkUrl: 'https://example/x?response-content-disposition=attachment%3B%20filename%3D%22multiemu-1.0.exe%22&x-id=GetObject',
};

assert.strictEqual(shared.isWindowsRelease(androidRelease), false);
assert.strictEqual(shared.isWindowsRelease(windowsRelease), true);

// No filename to read: fall back to minAndroidSdk, and treat anything that
// looks like neither as not ours.
assert.strictEqual(shared.isWindowsRelease({ apkUrl: null, minAndroidSdk: 24 }), false);
assert.strictEqual(shared.isWindowsRelease({ apkUrl: null, minAndroidSdk: null }), true);

// --- Cloud save identity -----------------------------------------------
//
// This one is a contract with the Android app, not a local choice: the two
// only ever see each other's saves if the key matches exactly. It was wrong
// in all three ways at once once already -- no system prefix, zero-padded
// hex, and the battery save uploaded to a save-state slot.
assert.strictEqual(
  shared.cloudGameKey('gba', new Uint8Array(Buffer.from('multiemu'))),
  'gba:1bf63dba',
);
assert.strictEqual(
  shared.cloudGameKey('nds', new Uint8Array(Buffer.from('multiemu'))),
  'nds:1bf63dba',
);

// A CRC32 whose top nibble is zero must stay seven characters. Padding it
// to eight is what Android would never produce.
assert.strictEqual(
  shared.cloudGameKey('gb', new Uint8Array(Buffer.from('multiemu-0'))),
  'gb:1686969',
);

// --- Encoding ----------------------------------------------------------
//
// Every string the user sees is Spanish, and an editor or a script writing
// a file as cp1252 instead of UTF-8 turns one accent into a replacement
// character in the UI while everything still builds and runs. Cheap to
// check, and it already caught four files.
for (const file of [
  'src/hub.js',
  'src/main.js',
  'src/preload.js',
  'src/renderer/hub.js',
  'src/renderer/renderer.js',
  'src/renderer/audio.js',
  'src/renderer/index.html',
  'README.md',
]) {
  const bytes = fs.readFileSync(path.join(__dirname, '..', file));
  assert.ok(
    Buffer.compare(Buffer.from(bytes.toString('utf8'), 'utf8'), bytes) === 0,
    `${file} is not valid UTF-8`,
  );
}

console.log('smoke: ok');
